### ISSUE TITLE
Can't run benchmarks on fresh install

### ISSUE THREAD

**Issue by mhewett-ks** [ConsenSys/mikuli#7]
Clone, build, and test worked but not benchmarks.  Java 1.8.0_201 on an updated Mac.

```
$ git clone git@github.com:ConsenSys/mikuli.git
Cloning into 'mikuli'...
remote: Enumerating objects: 288, done.
remote: Total 288 (delta 0), reused 0 (delta 0), pack-reused 288
Receiving objects: 100% (288/288), 53.50 KiB | 1014.00 KiB/s, done.
Resolving deltas: 100% (101/101), done.
✔ 
--------------------------------------------------------------
$ cd mikuli
✔ ~/work/sw/repos/mikuli [master|✔] 
$ gradle clean build
Starting a Gradle Daemon (subsequent builds will be faster)

> Task :test
SUCCESS (5 tests, 5 successes, 0 failures, 0 skipped)

BUILD SUCCESSFUL in 37s
6 actionable tasks: 6 executed
✔ ~/mikuli [master|✔] 
--------------------------------------------------------------
11:02 $ gradle test

BUILD SUCCESSFUL in 0s
3 actionable tasks: 3 up-to-date
✔ ~/mikuli [master|✔] 
--------------------------------------------------------------
11:02 $ gradle benchmark

> Task :benchmarks FAILED
Exception in thread "main" java.lang.RuntimeException: ERROR: Unable to find the resource: /META-INF/BenchmarkList
        at org.openjdk.jmh.runner.AbstractResourceReader.getReaders(AbstractResourceReader.java:98)
        at org.openjdk.jmh.runner.BenchmarkList.find(BenchmarkList.java:122)
        at org.openjdk.jmh.runner.Runner.internalRun(Runner.java:256)
        at org.openjdk.jmh.runner.Runner.run(Runner.java:206)
        at org.openjdk.jmh.Main.main(Main.java:71)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':benchmarks'.
> Process 'command '.sdkman/candidates/java/8.0.201-oracle/bin/java'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
5 actionable tasks: 2 executed, 3 up-to-date
```

**Comment by nkeywal** [comment]
@bkolad fwiw, it works with linux/java version "10.0.2" 2018-07-17 at least.

But from http://java-drobnosti.blogspot.com/2015/12/jmh-error-unable-to-find-resource-meta.html, may be a simple `gradle clean` is enough

**Comment by bkolad** [comment]
@mhewett-ks I think this is jmh and gradle compatibility problem:
https://www.gitmemory.com/issue/johnrengelman/shadow/464/472230390

**Comment by nkeywal** [comment]
![image](https://user-images.githubusercontent.com/1179343/60721747-3734d780-9f2f-11e9-98da-5f9d3b036a2c.png)

But only the 0.4.8 seems available in the default repo.
